# Generated by Django 4.2.5 on 2023-11-18 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0003_alter_show_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_shows', to=settings.AUTH_USER_MODEL),
        ),
    ]
