# Generated by Django 4.2.5 on 2023-11-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_show_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='commented_shows', to='user_app.comment'),
        ),
    ]
