# Generated by Django 4.2.5 on 2023-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
